<!doctype html><html lang="fr"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans;font-size:11px;color:#183027}h1{color:#176b45}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}.total{font-size:15px;text-align:right}.mark{background:#176b45;color:white;padding:12px;font-size:22px}footer{margin-top:30px;font-size:9px}</style></head><body>
@if(!empty($invoice->snapshot['gie']['logo_path']))<img src="{{ storage_path('app/public/'.$invoice->snapshot['gie']['logo_path']) }}" height="60" alt="Logo FRAINS">@endif
<div class="mark">FRAINS Agro</div><h1>Facture {{ $invoice->number }}</h1><p>Émise le {{ $invoice->issued_at->format('d/m/Y') }} · Commande {{ $invoice->snapshot['order_number'] }}</p>
<p><strong>{{ $invoice->snapshot['gie']['gie_name'] ?? 'Fraternité Agricole Les Inséparables' }}</strong><br>{{ $invoice->snapshot['gie']['address'] ?? '' }}<br>{{ $invoice->snapshot['gie']['phone'] ?? '' }} · {{ $invoice->snapshot['gie']['email'] ?? '' }}<br>{{ $invoice->snapshot['gie']['registration'] ?? '' }}</p>
<h2>Client</h2><p>{{ $invoice->snapshot['customer']['name'] }} · {{ $invoice->snapshot['customer']['company'] }}<br>{{ $invoice->snapshot['customer']['address'] }}</p>
<table><thead><tr><th>Produit</th><th>Quantité</th><th>Prix unitaire</th><th>Montant</th></tr></thead><tbody>@foreach($invoice->snapshot['items'] as $item)<tr><td>{{ $item['product_name'] }} {{ $item['packaging'] ?? '' }}</td><td>{{ $item['quantity'] }} {{ $item['unit'] }}</td><td>{{ number_format($item['unit_price'],2,',',' ') }}</td><td>{{ number_format($item['total'],2,',',' ') }}</td></tr>@endforeach</tbody></table>
<p class="total">Produits : {{ number_format($invoice->snapshot['subtotal'],2,',',' ') }} FCFA<br>Livraison : {{ number_format($invoice->snapshot['delivery_fee'],2,',',' ') }} FCFA<br>Remise : {{ number_format($invoice->snapshot['discount'],2,',',' ') }} FCFA<br><strong>Total : {{ number_format($invoice->snapshot['total'],2,',',' ') }} FCFA</strong><br>Payé : {{ number_format($order->paid_amount,2,',',' ') }} FCFA<br>Reste à payer : {{ number_format($order->balance,2,',',' ') }} FCFA</p>
@if($order->payment_due_date)<p>Échéance : {{ $order->payment_due_date->format('d/m/Y') }}</p>@endif
<footer>Situation des règlements au {{ now()->format('d/m/Y H:i') }}. Les informations de la vente sont conservées à l’émission.</footer></body></html>
