<x-layouts.admin title="Administration — FRAINS Agro"><section class="commerce admin-dashboard">
<p class="eyebrow">FRAINS AGRO · ESPACE DE GESTION</p><div class="section-heading"><div><h1>Tableau de bord</h1><p>Bonjour {{ auth()->user()->first_name }}. Voici la situation de votre activité.</p></div><a class="button" href="{{ route('admin.reports') }}">Rapports et statistiques</a></div>
<div class="dashboard-metrics">
@foreach(['Chiffre d’affaires livré (FCFA)'=>$turnover,'Commandes en cours'=>$pendingOrders,'Clients'=>$customerCount,'Produits'=>$productCount,'Livraisons à suivre'=>$deliveryCount,'Devis reçus'=>$newQuotes] as $label=>$value)<article><span>{{ $label }}</span><strong>{{ number_format($value,0,',',' ') }}</strong></article>@endforeach
</div>
<div class="dashboard-columns"><section class="panel"><div class="section-heading"><h2>Dernières commandes</h2><a href="{{ route('admin.orders.index') }}">Toutes les commandes →</a></div><div class="table-scroll"><table><thead><tr><th>Commande</th><th>Client</th><th>Étape</th><th>Total</th></tr></thead><tbody>@forelse($lastOrders as $order)<tr><td><a href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a></td><td>{{ $order->customer?->name }}</td><td><span class="status-pill">{{ \App\Models\Order::STATUSES[$order->status] }}</span></td><td>{{ number_format($order->total,0,',',' ') }} FCFA</td></tr>@empty<tr><td colspan="4">Les commandes apparaîtront ici dès leur réception.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Stocks à surveiller</h2>@forelse($lowStocks as $stock)<p class="low-stock"><strong>{{ $stock->product?->name }}</strong><br>{{ $stock->available_quantity }} {{ $stock->product?->unit }} disponibles · seuil {{ $stock->minimum_quantity }}</p>@empty<p>Aucune alerte de stock.</p>@endforelse @if(in_array(auth()->user()->role?->name,['ADMIN','MANAGER']))<p><a href="{{ route('admin.stocks.index') }}">Gérer les stocks →</a></p>@endif</section></div>
@if(in_array(auth()->user()->role?->name,['ADMIN','MANAGER']))<section class="panel"><h2>Production agricole</h2><p>{{ $producerCount }} producteur(s) enregistré(s). Les récoltes alimentent le stock après déduction des pertes.</p><a class="button" href="{{ route('admin.agriculture.index') }}">Suivre les productions et récoltes</a></section>@endif
</section></x-layouts.admin>
