<x-layouts.admin title="Rapports et alertes"><section class="commerce"><h1>Rapports, statistiques et alertes</h1><form class="filters"><label>Du<input type="date" name="from" value="{{ $from }}"></label><label>Au<input type="date" name="to" value="{{ $to }}"></label><button>Afficher</button><button name="export" value="csv">Exporter CSV</button></form><div class="metrics" style="margin-top:20px">@foreach($metrics as $label=>$value)<div><span>{{ $label }}</span><b>{{ number_format($value,2,',',' ') }}</b></div>@endforeach</div>
<p>Les opérations sont regroupées selon leur date de création ; les récoltes selon leur date de récolte. Les stocks et alertes représentent la situation actuelle.</p>
@foreach($charts as $chart)<section class="panel"><h2>{{ $chart['title'] }} ({{ $chart['unit'] }})</h2>@forelse($chart['points'] as $label=>$value)<p>{{ $label }} <progress aria-label="{{ $label }}" value="{{ $value }}" max="{{ max(1,$chart['points']->max()??1) }}"></progress> {{ number_format($value,2,',',' ') }} {{ $chart['unit'] }}</p>@empty<p>Aucune donnée sur cette période.</p>@endforelse</section>@endforeach
<h2>Alertes actuelles</h2><div class="panel">@foreach($stocks->filter(fn($s)=>$s->available_quantity<=$s->minimum_quantity) as $stock)<p>{{ $stock->available_quantity<=0?'Rupture':'Stock faible' }} : {{ $stock->product?->name }} ({{ $stock->available_quantity }} {{ $stock->product?->unit }})</p>@endforeach
@foreach($latePayments as $order)<p>Paiement en retard : <a href="{{ route('admin.orders.show',$order) }}">{{ $order->order_number }}</a> · {{ $order->balance }} FCFA</p>@endforeach
@foreach($lateDeliveries as $d)<p>Livraison en retard : {{ $d->delivery_number }} · {{ $d->scheduled_date->format('d/m/Y') }}</p>@endforeach<p>{{ $newQuotes }} nouvelle(s) demande(s) de devis.</p></div>
@if($monthly->isNotEmpty())<h2>Chiffre d’affaires livré par mois</h2><div class="panel">@foreach($monthly as $month=>$amount)<p>{{ $month }} <progress value="{{ $amount }}" max="{{ max(1,$monthly->max()) }}"></progress> {{ number_format($amount,2,',',' ') }} FCFA</p>@endforeach</div>@endif
@if($top->isNotEmpty())<h2>Produits les plus vendus</h2>@foreach($top as $item)<p>{{ $item['name'] }} : {{ $item['quantity'] }} {{ $item['unit'] }} · {{ $item['total'] }} FCFA</p>@endforeach @endif
@if($harvests->isNotEmpty())<h2>Production et pertes par produit</h2>@foreach($harvests->groupBy('cultivation.product_id') as $group)<p>{{ $group->first()->cultivation->product->name }} : récolté {{ $group->sum('quantity') }} ; pertes {{ $group->sum('loss_quantity') }} {{ $group->first()->cultivation->product->unit }}</p>@endforeach @endif
@if($deliveries->isNotEmpty())<h2>Livraisons par livreur</h2>@foreach($deliveries->groupBy(fn($d)=>$d->driver_name??'Non affecté') as $name=>$group)<p>{{ $name }} : {{ $group->where('status','DELIVERED')->count() }} livrée(s) / {{ $group->count() }}</p>@endforeach @endif
@if($messages->isNotEmpty())<h2>Messages de contact reçus</h2>@foreach($messages as $message)<article class="panel"><strong>{{ $message->subject }}</strong><p>{{ $message->name }} · {{ $message->email }} · {{ $message->phone }}</p><p style="white-space:pre-line">{{ $message->message }}</p></article>@endforeach @endif
@if($audit->isNotEmpty())<h2>Journal des 100 dernières actions</h2><div class="panel table-scroll"><table><tr><th>Date</th><th>Auteur</th><th>Action</th><th>Objet</th></tr>@foreach($audit as $log)<tr><td>{{ $log->created_at }}</td><td>{{ $log->user_id }}</td><td>{{ $log->action }}</td><td>{{ $log->subject }}</td></tr>@endforeach</table></div>@endif</section></x-layouts.admin>
