<x-layouts.admin title="Stocks"><section class="commerce"><h1>Stocks et mouvements</h1>
<form id="ajouter-stock" class="panel commerce-form" method="POST" action="{{ route('admin.stocks.store') }}">@csrf
<h2>Ajouter du stock</h2><p>Saisissez la quantité reçue : elle sera ajoutée au stock existant, sans modifier les réservations des commandes.</p>
<input type="hidden" name="type" value="SUPPLY" required>
<label>Produit<select name="product_id" required><option value="">Choisir un produit</option>@foreach($products as $p)<option value="{{ $p->id }}" @selected(old('product_id', request('product')) == $p->id)>{{ $p->name }} — {{ $p->sku }} ({{ $p->unit }})</option>@endforeach</select></label>
<label>Quantité à ajouter (dans l’unité du produit)<input name="quantity" type="number" step="0.01" min="0.01" max="999999999" value="{{ old('quantity') }}" required></label>
<label>Motif ou référence de l’entrée<input name="reason" maxlength="255" value="{{ old('reason') }}" placeholder="Ex. Réception fournisseur, bon n° 123" required></label>
<button class="button" @disabled($products->isEmpty())>Ajouter au stock</button>
@if($products->isEmpty())<p>Créez d’abord un produit dans le catalogue pour lui ajouter du stock.</p>@endif
</form><h2>État des stocks</h2><div class="panel table-scroll"><table><tr><th>Produit</th><th>Physique</th><th>Réservé</th><th>Disponible</th><th>Seuil</th></tr>@foreach($stocks as $stock)<tr><td>{{ $stock->product?->name }} ({{ $stock->product?->unit }})</td><td>{{ $stock->quantity }}</td><td>{{ $stock->reserved_quantity }}</td><td>{{ $stock->available_quantity }}</td><td>{{ $stock->minimum_quantity }}</td></tr>@endforeach</table></div>{{ $stocks->links() }}
<form class="panel commerce-form" method="POST" action="{{ route('admin.stocks.store') }}">@csrf<h2>Autres mouvements de stock</h2><label>Produit<select name="product_id" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} ({{ $p->unit }})</option>@endforeach</select></label><label>Type<select name="type" required>@foreach(['RETURN'=>'Retour','LOSS'=>'Perte','DAMAGE'=>'Produit endommagé','OTHER_OUT'=>'Autre sortie'] as $k=>$v)<option value="{{ $k }}">{{ $v }}</option>@endforeach</select></label><label>Quantité<input name="quantity" type="number" step="0.01" min="0.01" required></label><label>Motif / référence<input name="reason" maxlength="255" required></label><button class="button">Enregistrer</button></form>
<h2>100 derniers mouvements</h2><div class="panel table-scroll"><table><tr><th>Date</th><th>Produit</th><th>Type</th><th>Quantité</th><th>Motif</th><th>Auteur</th></tr>@foreach($movements as $m)<tr><td>{{ $m->created_at->format('d/m/Y H:i') }}</td><td>{{ $m->product?->name }}</td><td>{{ $m->type }}</td><td>{{ $m->quantity }}</td><td>{{ $m->reason }}</td><td>{{ $m->user?->name }}</td></tr>@endforeach</table></div></section></x-layouts.admin>
